# Generated by Django 4.2.16 on 2024-11-09 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 9, 7, 8, 0, 452640, tzinfo=datetime.timezone.utc)),
        ),
    ]
